# Generated by Django 5.0.6 on 2026-06-05 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this note.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short descriptive title for the note (max 255 chars).', max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text='Full body content of the note.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of when the note was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent update.')),
                ('owner', models.ForeignKey(help_text='The user who owns this note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
