# Generated by Django 5.0.6 on 2026-06-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_content_tag_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='bg-gray-100 text-gray-800', help_text='Tailwind color classes for the tag badge.', max_length=255),
        ),
    ]
