# Generated by Django 5.0.6 on 2026-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_note_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_favourite',
            field=models.BooleanField(default=False, help_text='Whether this note is marked as a favourite by the owner.'),
        ),
    ]
