# Generated by Django 5.0.6 on 2026-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_note_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the note was moved to trash.', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_trashed',
            field=models.BooleanField(default=False, help_text='Whether this note is in the trash.'),
        ),
        migrations.AddField(
            model_name='sharednote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharednote',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
