# Generated by Django 5.0.6 on 2026-06-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_note_deleted_at_note_is_trashed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(help_text='The note that contains the [[wikilink]].', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='api.note')),
                ('target', models.ForeignKey(help_text='The note being linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='api.note')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
