# Generated by Django 5.0.6 on 2026-06-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_notelink_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(db_index=True, help_text='Short descriptive title for the note (max 255 chars).', max_length=255),
        ),
    ]
